/**
 * Draws the application mark, at every size the project needs.
 *
 * A script rather than committed binaries alone: the tray icon that shipped
 * before this was a flat rectangle of one colour, which is what a mark becomes
 * when nobody can see how it was made. Here the shape is code, so it can be
 * read, corrected, and regenerated.
 *
 * Pure zlib and Buffer — an icon is not worth a dependency.
 */
import { deflateSync } from "node:zlib";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const BUILD = join(import.meta.dirname, "..", "build");

/** The mark: a book seen from the front, its spine to the left. */
const INK = [37, 99, 235, 255];        // the cover
const SPINE = [30, 64, 175, 255];      // the spine, a shade deeper
const PAGE = [248, 250, 252, 255];     // the page edge

/**
 * Paints one pixel of the mark, in a unit square.
 *
 * Working in fractions rather than pixels is what lets the same shape be a
 * 16-pixel tray icon and a 512-pixel application icon without two drawings
 * that drift apart.
 */
function sample(u, v) {
  // A margin, so the mark does not touch the edges of its box.
  if (u < 0.09 || u > 0.91 || v < 0.11 || v > 0.89) return null;

  // The rounded corners of the cover.
  const corner = (cu, cv) => Math.hypot(u - cu, v - cv);
  const r = 0.08;
  if (u < 0.09 + r && v < 0.11 + r && corner(0.09 + r, 0.11 + r) > r) return null;
  if (u > 0.91 - r && v < 0.11 + r && corner(0.91 - r, 0.11 + r) > r) return null;
  if (u < 0.09 + r && v > 0.89 - r && corner(0.09 + r, 0.89 - r) > r) return null;
  if (u > 0.91 - r && v > 0.89 - r && corner(0.91 - r, 0.89 - r) > r) return null;

  if (u < 0.30) return SPINE;                       // the spine
  if (u > 0.34 && u < 0.86 && v > 0.22 && v < 0.34) return PAGE;   // two page edges,
  if (u > 0.34 && u < 0.86 && v > 0.44 && v < 0.56) return PAGE;   // which read as
  if (u > 0.34 && u < 0.72 && v > 0.66 && v < 0.78) return PAGE;   // text at any size
  return INK;
}

function png(size) {
  const stride = 1 + size * 4;
  const raw = Buffer.alloc(stride * size);

  for (let y = 0; y < size; y++) {
    raw[y * stride] = 0;
    for (let x = 0; x < size; x++) {
      // The centre of the pixel, so a shape is not shifted half a pixel.
      const pixel = sample((x + 0.5) / size, (y + 0.5) / size) ?? [0, 0, 0, 0];
      raw.set(pixel, y * stride + 1 + x * 4);
    }
  }

  const chunk = (type, body) => {
    const out = Buffer.alloc(body.length + 12);
    out.writeUInt32BE(body.length, 0);
    out.write(type, 4, "latin1");
    body.copy(out, 8);
    out.writeInt32BE(crc(Buffer.concat([Buffer.from(type, "latin1"), body])), body.length + 8);
    return out;
  };

  const header = Buffer.alloc(13);
  header.writeUInt32BE(size, 0);
  header.writeUInt32BE(size, 4);
  header[8] = 8;   // bit depth
  header[9] = 6;   // RGBA
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk("IHDR", header),
    chunk("IDAT", deflateSync(raw, { level: 9 })),
    chunk("IEND", Buffer.alloc(0)),
  ]);
}

const TABLE = Array.from({ length: 256 }, (_, n) => {
  let c = n;
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c >>> 0;
});

function crc(buffer) {
  let c = 0xffffffff;
  for (const byte of buffer) c = TABLE[(c ^ byte) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) | 0;
}

await mkdir(BUILD, { recursive: true });
for (const size of [16, 32, 64, 128, 256, 512]) {
  await writeFile(join(BUILD, `icon-${size}.png`), png(size));
}
// electron-builder takes the largest as the source for every Linux size.
await writeFile(join(BUILD, "icon.png"), png(512));

// Inlined into the sources rather than read from disk at runtime: the main
// bundle moves between `dist/` and a packaged archive, and a mark that depends
// on finding a file next to it is a mark that disappears once packaged.
await writeFile(
  join(import.meta.dirname, "..", "main", "icons.ts"),
  [
    "/** Generated by scripts/make-icons.mjs — edit the script, not this file. */",
    "",
    "/** 32px: what the system tray shows.  */",
    `export const TRAY_ICON =\n  "data:image/png;base64,${png(32).toString("base64")}";`,
    "",
    "/** 128px: the window's own icon, and the mark on the splash. */",
    `export const APP_ICON =\n  "data:image/png;base64,${png(128).toString("base64")}";`,
    "",
  ].join("\n"),
);

console.log("icons written to app/build");
